let
    AddFunctionCall=List.Generate(()=>[Page Number=0,Func=null], each (try _[Func])[HasError]=false, each [Page Number=_[Page Number]+1, Func=fnGetExpenses([Page Number]+1)], each _[Func]),
    #"Converted to Table" = Table.FromList(AddFunctionCall, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandTableColumn(#"Converted to Table", "Column1", {"id", "spent_date", "notes", "total_cost", "units", "billable", "receipt", "is_closed", "is_locked", "is_billed", "locked_reason", "created_at", "updated_at", "id.1", "name", "id.2", "name.1", "currency", "id.3", "name.2", "code", "id.4", "name.3", "unit_price", "unit_name", "id.5", "is_project_manager", "is_active", "budget", "created_at.1", "updated_at.1", "hourly_rate", "id.6", "number"}, {"id", "spent_date", "notes", "total_cost", "units", "billable", "receipt", "is_closed", "is_locked", "is_billed", "locked_reason", "created_at", "updated_at", "id.1", "name", "id.2", "name.1", "currency", "id.3", "name.2", "code", "id.4", "name.3", "unit_price", "unit_name", "id.5", "is_project_manager", "is_active", "budget", "created_at.1", "updated_at.1", "hourly_rate", "id.6", "number"}),
    #"Lignes filtrées" = Table.SelectRows(#"Expanded Column1", each [id] <> null and [id] <> ""),
    #"Colonnes renommées" = Table.RenameColumns(#"Lignes filtrées",{{"id", "Expense_id"}, {"notes", "Expense_notes"}, {"total_cost", "Expense_cost"}, {"units", "Expense_units"}}),
    #"receipt développé" = Table.ExpandRecordColumn(#"Colonnes renommées", "receipt", {"file_name"}, {"receipt.file_name"}),
    #"Colonnes renommées1" = Table.RenameColumns(#"receipt développé",{{"receipt.file_name", "receipt_file_name"}, {"id.2", "Client_id"}, {"name.1", "Client_name"}, {"id.3", "Project_id"}, {"name.2", "Project_name"}, {"code", "Project_code"}, {"name.3", "ExpenseCat_name"}, {"id.4", "ExpenseCat_id"}, {"id.5", "Project_user_id"}, {"created_at.1", "Project_user_created"}, {"updated_at.1", "Project_user_updated"}, {"id.6", "Invoice_id"}, {"number", "Invoice_number"}}),
    #"Type modifié" = Table.TransformColumnTypes(#"Colonnes renommées1",{{"Expense_id", Int64.Type}, {"spent_date", type date}, {"Expense_notes", type text}, {"Expense_cost", type number}, {"Expense_units", type number}, {"billable", type logical}, {"receipt_file_name", type text}, {"is_closed", type logical}, {"is_locked", type logical}, {"is_billed", type logical}, {"locked_reason", type text}, {"created_at", type datetime}, {"updated_at", type datetime}}),
    #"Colonnes renommées2" = Table.RenameColumns(#"Type modifié",{{"id.1", "User_id"}, {"name", "User_name"}}),
    #"Type modifié1" = Table.TransformColumnTypes(#"Colonnes renommées2",{{"User_id", Int64.Type}, {"User_name", type text}, {"Client_id", Int64.Type}, {"Client_name", type text}, {"currency", type text}, {"Project_id", type text}, {"Project_name", type text}, {"Project_code", type text}, {"ExpenseCat_id", Int64.Type}, {"ExpenseCat_name", type text}, {"unit_price", type number}, {"unit_name", type text}, {"Project_user_id", Int64.Type}, {"is_project_manager", type logical}, {"is_active", type logical}, {"budget", type number}, {"Project_user_created", type datetime}, {"Project_user_updated", type datetime}, {"hourly_rate", type number}, {"Invoice_id", Int64.Type}, {"Invoice_number", type text}})
in
    #"Type modifié1"
