let
    AddFunctionCall=List.Generate(()=>[Page Number=0,Func=null], each (try _[Func])[HasError]=false, each [Page Number=_[Page Number]+1, Func=fnGetInvoices([Page Number]+1)], each _[Func]),
    #"Converted to Table" = Table.FromList(AddFunctionCall, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandTableColumn(#"Converted to Table", "Column1", {"id", "client_key", "number", "purchase_order", "amount", "due_amount", "tax", "tax_amount", "tax2", "tax2_amount", "discount", "discount_amount", "subject", "notes", "state", "period_start", "period_end", "issue_date", "due_date", "payment_term", "sent_at", "paid_at", "closed_at", "created_at", "updated_at", "paid_date", "currency", "client", "estimate", "retainer", "id.1", "name", "line_items"}, {"id", "client_key", "number", "purchase_order", "amount", "due_amount", "tax", "tax_amount", "tax2", "tax2_amount", "discount", "discount_amount", "subject", "notes", "state", "period_start", "period_end", "issue_date", "due_date", "payment_term", "sent_at", "paid_at", "closed_at", "created_at", "updated_at", "paid_date", "currency", "client", "estimate", "retainer", "id.1", "name", "line_items"}),
    #"Lignes filtrées" = Table.SelectRows(#"Expanded Column1", each [id] <> null and [id] <> ""),
    #"Colonnes renommées" = Table.RenameColumns(#"Lignes filtrées",{{"id", "Invoice_id"}, {"number", "Invoice_number"}}),
    #"client développé" = Table.ExpandRecordColumn(#"Colonnes renommées", "client", {"id", "name"}, {"client.id", "client.name"}),
    #"Colonnes renommées1" = Table.RenameColumns(#"client développé",{{"client.id", "client_id"}, {"client.name", "client_name"}, {"id.1", "User_id"}, {"name", "User_name"}}),
    #"Type modifié" = Table.TransformColumnTypes(#"Colonnes renommées1",{{"Invoice_id", Int64.Type}, {"client_key", type text}, {"Invoice_number", type text}, {"purchase_order", type text}, {"amount", type number}, {"due_amount", type number}, {"tax", type number}, {"tax_amount", type number}, {"tax2", type number}, {"tax2_amount", type number}, {"discount", type number}, {"discount_amount", type number}, {"subject", type text}, {"notes", type text}, {"state", type text}, {"period_start", type date}, {"period_end", type date}, {"issue_date", type date}, {"due_date", type date}, {"payment_term", type text}, {"sent_at", type datetime}, {"paid_at", type datetime}, {"closed_at", type datetime}, {"created_at", type datetime}, {"updated_at", type datetime}, {"paid_date", type datetime}, {"currency", type text}, {"client_id", Int64.Type}, {"client_name", type text}, {"estimate", type number}, {"retainer", type number}, {"User_id", Int64.Type}, {"User_name", type text}}),
    #"Colonnes supprimées" = Table.RemoveColumns(#"Type modifié",{"line_items"})
in
    #"Colonnes supprimées"
