let
    AddFunctionCall=List.Generate(()=>[Page Number=0,Func=null], each (try _[Func])[HasError]=false, each [Page Number=_[Page Number]+1, Func=fnGetProjects([Page Number]+1)], each _[Func]),
    #"Converted to Table" = Table.FromList(AddFunctionCall, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandTableColumn(#"Converted to Table", "Column1", {"id", "name", "code", "is_active", "is_billable", "is_fixed_fee", "bill_by", "budget", "budget_by", "notify_when_over_budget", "over_budget_notification_percentage", "show_budget_to_all", "created_at", "updated_at", "starts_on", "ends_on", "over_budget_notification_date", "notes", "cost_budget", "cost_budget_include_expenses", "hourly_rate", "fee", "id.1", "name.1", "currency"}, {"id", "name", "code", "is_active", "is_billable", "is_fixed_fee", "bill_by", "budget", "budget_by", "notify_when_over_budget", "over_budget_notification_percentage", "show_budget_to_all", "created_at", "updated_at", "starts_on", "ends_on", "over_budget_notification_date", "notes", "cost_budget", "cost_budget_include_expenses", "hourly_rate", "fee", "id.1", "name.1", "currency"}),
    #"Colonnes renommées" = Table.RenameColumns(#"Expanded Column1",{{"id", "Project_id"},{"name", "Project_name"}, {"id.1", "Client_id"}, {"name.1", "Client_name"}}),
    #"Lignes filtrées" = Table.SelectRows(#"Colonnes renommées", each [Project_id] <> null and [Project_id] <> ""),
    #"Type modifié" = Table.TransformColumnTypes(#"Lignes filtrées",{{"Project_id", type text}, {"Project_name", type text}, {"code", type text}, {"is_active", type logical}, {"is_billable", type logical}, {"is_fixed_fee", type logical}, {"bill_by", type text}, {"budget", type number}, {"budget_by", type text}, {"notify_when_over_budget", type logical}, {"over_budget_notification_percentage", type number}, {"show_budget_to_all", type logical}, {"created_at", type datetime}, {"updated_at", type datetime}, {"starts_on", type date}, {"ends_on", type date}, {"over_budget_notification_date", type date}, {"notes", type text}, {"cost_budget", type number}, {"cost_budget_include_expenses", type logical}, {"hourly_rate", type number}, {"fee", type number}, {"Client_id", Int64.Type}, {"currency", type text}})
in
    #"Type modifié"
