let
    HelpersLocal = try Helpers otherwise null,
    HelpersRecord = if HelpersLocal <> null then HelpersLocal else (try Expression.Evaluate(Text.FromBinary(Web.Contents("https://raw.githubusercontent.com/jeanmarieletallec/Harvest/main/Helpers.pq")), #shared) otherwise null),
    fetch = (p) => fnGetTasks(p),
    all = if (HelpersRecord <> null and Record.HasFields(HelpersRecord, "FetchAllPages")) then HelpersRecord[FetchAllPages](fetch) else error "Helpers.FetchAllPages not found - import Helpers or enable remote fetch",
    #"Column1 développé" = Table.ExpandTableColumn(all, "Column1", {"id", "name", "billable_by_default", "default_hourly_rate", "is_default", "is_active", "created_at", "updated_at", "code", "is_billable", "is_fixed_fee", "bill_by", "budget", "budget_by", "notify_when_over_budget", "over_budget_notification_percentage", "show_budget_to_all", "starts_on", "ends_on", "over_budget_notification_date", "notes", "cost_budget", "cost_budget_include_expenses", "hourly_rate", "fee", "id.1", "name.1", "currency"}, {"id", "name", "billable_by_default", "default_hourly_rate", "is_default", "is_active", "created_at", "updated_at", "code", "is_billable", "is_fixed_fee", "bill_by", "budget", "budget_by", "notify_when_over_budget", "over_budget_notification_percentage", "show_budget_to_all", "starts_on", "ends_on", "over_budget_notification_date", "notes", "cost_budget", "cost_budget_include_expenses", "hourly_rate", "fee", "id.1", "name.1", "currency"}),
    #"Lignes filtrées" = Table.SelectRows(#"Column1 développé", each [id] <> null and [id] <> ""),
    #"Colonnes renommées" = Table.RenameColumns(#"Lignes filtrées",{{"id", "Task_id"}}),
    #"Type modifié" = Table.TransformColumnTypes(#"Colonnes renommées",{{"Task_id", Int64.Type}, {"name", type text}, {"billable_by_default", type logical}, {"default_hourly_rate", type number}, {"is_default", type logical}, {"is_active", type logical}, {"created_at", type datetime}, {"updated_at", type datetime}, {"code", type text}, {"is_billable", type logical}, {"is_fixed_fee", type logical}, {"bill_by", type text}, {"budget", type number}, {"budget_by", type text}, {"notify_when_over_budget", type logical}, {"over_budget_notification_percentage", type number}, {"show_budget_to_all", type logical}, {"starts_on", type date}, {"ends_on", type date}, {"over_budget_notification_date", type date}, {"notes", type text}, {"cost_budget", type number}, {"cost_budget_include_expenses", type logical}, {"hourly_rate", type number}, {"fee", type number}, {"id.1", Int64.Type}, {"name.1", type text}, {"currency", type text}})
in
    #"Type modifié"
