let
    HelpersRecord = try Expression.Evaluate(Text.FromBinary(Web.Contents("https://raw.githubusercontent.com/jeanmarieletallec/Harvest/main/Helpers.pq")), #shared) otherwise null,
    fetch = (p) => fnGetTimeSheetsData(p),
    all = if (HelpersRecord <> null and Record.HasFields(HelpersRecord, "FetchAllPages")) then HelpersRecord[FetchAllPages](fetch) else error "Helpers.FetchAllPages not found - import Helpers or enable remote fetch",
    #"Expanded Column1" = Table.ExpandTableColumn(all, "Column1", {"id", "spent_date", "hours", "notes", "is_locked", "locked_reason", "is_closed", "is_billed", "timer_started_at", "started_time", "ended_time", "is_running", "billable", "budgeted", "billable_rate", "cost_rate", "created_at", "updated_at", "user.id", "user.name", "client.id", "client.name", "client.currency", "project.id", "project.name", "project.code", "task.id", "task.name", "user_assignment.id", "user_assignment.is_project_manager", "user_assignment.is_active", "user_assignment.budget", "user_assignment.created_at", "user_assignment.updated_at", "user_assignment.hourly_rate", "task_assignment", "invoice", "external_reference"}, {"id", "spent_date", "hours", "notes", "is_locked", "locked_reason", "is_closed", "is_billed", "timer_started_at", "started_time", "ended_time", "is_running", "billable", "budgeted", "billable_rate", "cost_rate", "created_at", "updated_at", "user.id", "user.name", "client.id", "client.name", "client.currency", "project.id", "project.name", "project.code", "task.id", "task.name", "user_assignment.id", "user_assignment.is_project_manager", "user_assignment.is_active", "user_assignment.budget", "user_assignment.created_at", "user_assignment.updated_at", "user_assignment.hourly_rate", "task_assignment", "invoice", "external_reference"}),
    #"Lignes filtrées" = Table.SelectRows(#"Expanded Column1", each [id] <> null and [id] <> ""),
    #"Colonnes renommées" = Table.RenameColumns(#"Lignes filtrées",{{"user.id", "user_id"}, {"user.name", "user_name"}, {"client.id", "client_id"}, {"client.name", "client_name"}, {"project.id", "project_id"}, {"project.name", "project_name"}, {"project.code", "project_code"}, {"task.id", "task_id"}, {"task.name", "task_name"}, {"user_assignment.id", "user_assignment_id"}}),
    #"task_assignment développé" = Table.ExpandRecordColumn(#"Colonnes renommées", "task_assignment", {"id", "billable", "is_active", "created_at", "updated_at", "hourly_rate", "budget"}, {"id.1", "billable.1", "is_active", "created_at.1", "updated_at.1", "hourly_rate", "budget"}),
    #"Colonnes renommées1" = Table.RenameColumns(#"task_assignment développé",{{"id.1", "Task_Assignment_id"}, {"billable.1", "Task_Assignment_is_billable"}, {"created_at.1", "Task_Assignment_created_at"}, {"updated_at.1", "Task_Assignment_updated_at"}}),
    #"invoice développé" = Table.ExpandRecordColumn(#"Colonnes renommées1", "invoice", {"id", "number"}, {"id.1", "number"}),
    #"Colonnes renommées2" = Table.RenameColumns(#"invoice développé",{{"id.1", "Invoice_id"}, {"number", "Invoice_number"}, {"id", "Time_id"}}),
    #"Type modifié" = Table.TransformColumnTypes(#"Colonnes renommées2",{{"Time_id", Int64.Type}, {"spent_date", type date}, {"hours", type number}, {"notes", type text}, {"is_locked", type logical}, {"locked_reason", type text}, {"is_closed", type logical}, {"is_billed", type logical}, {"timer_started_at", type datetime}, {"started_time", type duration}, {"ended_time", type duration}, {"is_running", type logical}, {"billable", type logical}, {"budgeted", type logical}, {"billable_rate", type number}, {"cost_rate", type number}, {"created_at", type datetime}, {"updated_at", type datetime}, {"user_id", Int64.Type}, {"user_name", type text}, {"client_id", Int64.Type}, {"client_name", type text}, {"client.currency", type text}, {"project_id", type text}, {"project_name", type text}, {"project_code", type text}, {"task_id", Int64.Type}, {"task_name", type text}, {"user_assignment_id", Int64.Type}, {"user_assignment.is_project_manager", type logical}, {"user_assignment.is_active", type logical}, {"user_assignment.budget", type logical}, {"user_assignment.created_at", type datetime}, {"user_assignment.updated_at", type datetime}, {"user_assignment.hourly_rate", type number}, {"Task_Assignment_id", Int64.Type}, {"Task_Assignment_is_billable", type logical}, {"is_active", type logical}, {"Task_Assignment_created_at", type datetime}, {"Task_Assignment_updated_at", type datetime}, {"hourly_rate", type number}, {"budget", type number}, {"Invoice_id", Int64.Type}, {"Invoice_number", type text}, {"external_reference", type text}})
in
    #"Type modifié"
